services:
  - type: web
    name: jb-rice-pro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jb-rice-pro-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: Africa/Nairobi

databases:
  - name: jb-rice-pro-db
    databaseName: jbricepro
    user: jbricepro 